In [168]:
import importlib
import NOT_sentence_generator2
importlib.reload(NOT_sentence_generator2)

### 1. Baseline: single NOT, positive

In [169]:
base_df = NOT_sentence_generator2.generate_base(adj_sentiment="both", seed=8)
print(base_df["adj_sentiment"].value_counts())

adj_sentiment
positive    36
negative    34
Name: count, dtype: int64

In [165]:
base_df

    id    domain               base            adj adj_sentiment
0    1      film      The movie was  unforgettable      positive
1    2      film       The film was       overlong      negative
2    3      film       The plot was      confusing      negative
3    4      film     The acting was      masterful      positive
4    5      film     The ending was       gripping      positive
..  ..       ...                ...            ...           ...
65  66  products    The blender was         sturdy      positive
66  67  products    The battery was        precise      positive
67  68  products     The screen was     overpriced      negative
68  69  products     The design was         flimsy      negative
69  70  products  The packaging was         sturdy      positive

[70 rows x 5 columns]

In [151]:
df1 =  NOT_sentence_generator2.apply_not(base_df, n_not=1)
df1.head()

,id,domain,base,adj,adj_sentiment,n_not,contraction,not_at,aux_not,label,sentence
0,1,film,The movie was,compelling,positive,1,False,False,False,negative,"Even so, the movie was not compelling"
1,2,film,The film was,derivative,negative,1,False,False,False,positive,I have to say the film was not derivative
2,3,film,The plot was,pretentious,negative,1,False,False,False,positive,"Honestly, the plot was not pretentious"
3,4,film,The acting was,captivating,positive,1,False,False,False,negative,"All things considered, the acting was not capt..."
4,5,film,The ending was,brilliant,positive,1,False,False,False,negative,"At the end of the day, the ending was not bril..."

In [166]:
df1 =  NOT_sentence_generator2.apply_not(base_df, n_not=2, contraction=True)
df1.head()

,id,domain,base,adj,adj_sentiment,n_not,contraction,not_at,aux_not,label,sentence
0,1,film,The movie was,unforgettable,positive,2,True,False,False,positive,"Even so, the movie wasn't not unforgettable"
1,2,film,The film was,overlong,negative,2,True,False,False,negative,I have to say the film wasn't not overlong
2,3,film,The plot was,confusing,negative,2,True,False,False,negative,"Honestly, the plot wasn't not confusing"
3,4,film,The acting was,masterful,positive,2,True,False,False,positive,"All things considered, the acting wasn't not m..."
4,5,film,The ending was,gripping,positive,2,True,False,False,positive,"At the end of the day, the ending wasn't not g..."

In [156]:
df1 =  NOT_sentence_generator2.apply_not(base_df, not_at=True, n_not=0)
df1.head()

,id,domain,base,adj,adj_sentiment,n_not,contraction,not_at,aux_not,label,sentence
0,1,film,The movie was,compelling,positive,0,False,True,False,negative,"NOT Even so, the movie was compelling"
1,2,film,The film was,derivative,negative,0,False,True,False,positive,NOT I have to say the film was derivative
2,3,film,The plot was,pretentious,negative,0,False,True,False,positive,"NOT Honestly, the plot was pretentious"
3,4,film,The acting was,captivating,positive,0,False,True,False,negative,"NOT All things considered, the acting was capt..."
4,5,film,The ending was,brilliant,positive,0,False,True,False,negative,"NOT At the end of the day, the ending was bril..."

In [170]:
df1 =  NOT_sentence_generator2.apply_not(base_df, n_not=1, aux_not=True)
df1.head()

,id,domain,base,adj,adj_sentiment,n_not,contraction,not_at,aux_not,label,sentence
0,1,film,The movie was,unforgettable,positive,1,False,False,True,negative,Everyone could not tell that the movie was not...
1,2,film,The film was,overlong,negative,1,False,False,True,positive,I would not go back: the film was not overlong
2,3,film,The plot was,confusing,negative,1,False,False,True,positive,I could not wait to leave because the plot was...
3,4,film,The acting was,masterful,positive,1,False,False,True,negative,I will not forget that the acting was not mast...
4,5,film,The ending was,gripping,positive,1,False,False,True,negative,I could not help but notice that the ending wa...

## 2. NOT composition

In [137]:
for n in [1, 2, 3]:
    df = NOT_sentence_generator2.generate_not_sentences(sentiment='both', n_not=n)
    print(f'n_not={n}:', df.sentence.iloc[0])

TypeError: generate_not_sentences() got an unexpected keyword argument 'sentiment'

In [120]:
df

    id    domain               base          adj adj_sentiment
0    1      film      The movie was   compelling      positive
1    2      film       The film was   derivative      negative
2    3      film       The plot was  pretentious      negative
3    4      film     The acting was  captivating      positive
4    5      film     The ending was    brilliant      positive
..  ..       ...                ...          ...           ...
65  66  products    The blender was    intuitive      positive
66  67  products    The battery was   unreliable      negative
67  68  products     The screen was      fragile      negative
68  69  products     The design was      precise      positive
69  70  products  The packaging was   overpriced      negative

[70 rows x 5 columns]

In [65]:
len(df)

70

## 3. Contraction (wasn't)

In [77]:
for n in [1, 2, 3]:
    df = NOT_sentence_generator2.generate_not_sentences(adj_sentiment='both', n_not=n, contraction=True)
    print(f'n_not={n}:', df.sentence.iloc[0])

n_not=1: The movie wasn't captivating
n_not=2: The movie wasn't not captivating
n_not=3: The movie wasn't not not captivating

In [78]:
df

,id,domain,base,adjs,adj_sentiment,n_not,contraction,not_at,aux_not,label,sentence
0,1,film,The movie was,captivating,positive,3,True,False,False,negative,The movie wasn't not not captivating
1,2,film,The film was,masterful,positive,3,True,False,False,negative,The film wasn't not not masterful
2,3,film,The plot was,derivative,negative,3,True,False,False,positive,The plot wasn't not not derivative
3,4,film,The acting was,unforgettable,positive,3,True,False,False,negative,The acting wasn't not not unforgettable
4,5,film,The ending was,compelling,positive,3,True,False,False,negative,The ending wasn't not not compelling
...,...,...,...,...,...,...,...,...,...,...,...
65,66,places,The landscape was,run-down,negative,3,True,False,False,positive,The landscape wasn't not not run-down
66,67,products,The battery was,responsive,positive,3,True,False,False,negative,The battery wasn't not not responsive
67,68,products,The screen was,unreliable,negative,3,True,False,False,positive,The screen wasn't not not unreliable
68,69,products,The design was,impressive,positive,3,True,False,False,negative,The design wasn't not not impressive
69,70,products,The packaging was,precise,positive,3,True,False,False,negative,The packaging wasn't not not precise

In [79]:
df = NOT_sentence_generator2.generate_not_sentences(adj_sentiment='both', n_not=2, contraction=True)

In [80]:
df.head()

,id,domain,base,adjs,adj_sentiment,n_not,contraction,not_at,aux_not,label,sentence
0,1,film,The movie was,captivating,positive,2,True,False,False,positive,The movie wasn't not captivating
1,2,film,The film was,masterful,positive,2,True,False,False,positive,The film wasn't not masterful
2,3,film,The plot was,derivative,negative,2,True,False,False,negative,The plot wasn't not derivative
3,4,film,The acting was,unforgettable,positive,2,True,False,False,positive,The acting wasn't not unforgettable
4,5,film,The ending was,compelling,positive,2,True,False,False,positive,The ending wasn't not compelling

## 4. not_at — NOT at the beginning

In [47]:
df =  NOT_sentence_generator.generate_not_sentences(adj_sentiment='both', n_not=1, not_at=True)
df.head

  domain                                           sentence     label
0   film        NOT At worst, the movie was not pretentious  negative
1   film  NOT Right from the beginning, the film was not...  negative
2   film       NOT Admittedly, the plot was not predictable  negative
3   film   NOT I have to say the acting was not predictable  negative
4   film  NOT Right from the beginning, the ending was n...  negative

In [48]:
df.head()

,id,domain,base,adjs,adj_sentiment,n_not,contraction,not_at,aux_not,sentence,label
0,1,film,The movie was,pretentious,negative,1,False,True,False,"NOT At worst, the movie was not pretentious",negative
1,2,film,The film was,boring,negative,1,False,True,False,"NOT Right from the beginning, the film was not...",negative
2,3,film,The plot was,predictable,negative,1,False,True,False,"NOT Admittedly, the plot was not predictable",negative
3,4,film,The acting was,predictable,negative,1,False,True,False,NOT I have to say the acting was not predictable,negative
4,5,film,The ending was,boring,negative,1,False,True,False,"NOT Right from the beginning, the ending was n...",negative

## 5. aux_not — carrier clause

In [50]:
df = NOT_sentence_generator.generate_not_sentences(adj_sentiment='positive', n_not=2, aux_not=True)
df[['domain', 'sentence']].head(5)

  domain                                           sentence
0   film  You could not deny that the movie was not not ...
1   film  I could not help but notice that the film was ...
2   film  I could not help but notice that the plot was ...
3   film  I could not wait to leave because the acting w...
4   film  It was not clear to me that the ending was not...

In [53]:
df.head()

,id,domain,base,adjs,adj_sentiment,n_not,contraction,not_at,aux_not,sentence,label
0,1,film,The movie was,masterful,positive,2,False,False,True,You could not deny that the movie was not not ...,positive
1,2,film,The film was,unforgettable,positive,2,False,False,True,I could not help but notice that the film was ...,positive
2,3,film,The plot was,brilliant,positive,2,False,False,True,I could not help but notice that the plot was ...,positive
3,4,film,The acting was,compelling,positive,2,False,False,True,I could not wait to leave because the acting w...,positive
4,5,film,The ending was,brilliant,positive,2,False,False,True,It was not clear to me that the ending was not...,positive

## 6. Pin a specific aux template

In [52]:
for t in [0, 1, 2, 3]:
    df = NOT_sentence_generator.generate_not_sentences(adj_sentiment='positive', n_not=1, aux_not=True, template_idx=t)
    print(f'template {t}:', df.sentence.iloc[0])

TypeError: generate_not_sentences() got an unexpected keyword argument 'template_idx'

## 7. Sentiment — positive vs negative vs both

In [16]:
for s in ['positive', 'negative', 'both']:
    df = generate_not_sentences(sentiment=s, n_not=1)
    print(f'{s}:', df[df.domain == 'food'].sentence.iloc[0])

positive: Let us be clear, the pasta was not tender
negative: Let us be clear, the pasta was not soggy
both: Let us be clear, the pasta was not heavenly

## 9. Combine parameters

In [17]:
df = generate_not_sentences(sentiment='positive', n_not=2, not_at=True, aux_not=True)
df[['domain', 'sentence']].head(5)

  domain                                           sentence
0   film  NOT I could not wait to leave because the movi...
1   film  NOT I could not stop thinking about how the fi...
2   film  NOT I could not believe that the plot was not ...
3   film  NOT Everyone could not tell that the acting wa...
4   film  NOT I would not go back: the ending was not no...